<?php

namespace Database\Seeders;

use App\Models\IpgModel;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Log;

class IpgModelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Log::info('Starting IpgModelSeeder...');

        $models = [
            ['model_number' => '122456', 'model_name' => 'PHILOS SLR', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '123459', 'model_name' => 'Philos S', 'device_type' => 'Single Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '123460', 'model_name' => 'Philos SR', 'device_type' => 'Single Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '123461', 'model_name' => 'Philos D', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '123462', 'model_name' => 'Cylos 990 DR-T', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '123464', 'model_name' => 'Cylos 990 DR-T', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '123465', 'model_name' => 'Philos DR', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '338202', 'model_name' => 'STRATOS LV-T', 'device_type' => 'Triple Chamber Brady', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '338847', 'model_name' => 'AXIOS S', 'device_type' => 'Single Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 73000, 'mr_enabled' => false],
            ['model_number' => '341822', 'model_name' => 'PHILOS II SLR', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '341823', 'model_name' => 'PHILOS II S', 'device_type' => 'Single Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '341824', 'model_name' => 'PHILOS II SR', 'device_type' => 'Single Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '341825', 'model_name' => 'PHILOS II D', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '341826', 'model_name' => 'PHILOS II DR', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '355262', 'model_name' => 'LUMAX 300 HF-T', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '355263', 'model_name' => 'LUMAX 340 HF-T', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '355266', 'model_name' => 'LUMAX 300 DR-T', 'device_type' => 'Dual Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '355267', 'model_name' => 'Lumax 340 DR-T', 'device_type' => 'Dual Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '355269', 'model_name' => 'LUMAX 340 VR', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '355270', 'model_name' => 'Lumax 300 VR-T', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '355271', 'model_name' => 'LUMAX 340 VR-T', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '356245', 'model_name' => 'TALOS D', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '356248', 'model_name' => 'TALOS DR', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '356250', 'model_name' => 'TALOS S', 'device_type' => 'Single Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '356252', 'model_name' => 'TALOS SLR', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '356254', 'model_name' => 'TALOS SR', 'device_type' => 'Single Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '359528', 'model_name' => 'EVIA DR Coated', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '359532', 'model_name' => 'EVIA SR Coated', 'device_type' => 'Single Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '360346', 'model_name' => 'Lumax 540 DR-T', 'device_type' => 'Dual Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '360347', 'model_name' => 'LUMAX 540 HF-T', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '360348', 'model_name' => 'Lumax 540 VR-T', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '368852', 'model_name' => 'Lumax 540 VR-T DX', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '371199', 'model_name' => 'Effecta DR', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 73000, 'mr_enabled' => false],
            ['model_number' => '371200', 'model_name' => 'Estella SR-T', 'device_type' => 'Single Chamber Brady', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '371202', 'model_name' => 'Effecta SR', 'device_type' => 'Single Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 73000, 'mr_enabled' => false],
            ['model_number' => '371996', 'model_name' => 'EVIA DR-T MRI', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '371997', 'model_name' => 'EVIA SR MRI', 'device_type' => 'Single Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '371998', 'model_name' => 'EVIA SR-T', 'device_type' => 'Single Chamber Brady', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '372418', 'model_name' => 'LUMAX 640 VRT-DX', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '375429', 'model_name' => 'EFFECTA D', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 73000, 'mr_enabled' => false],
            ['model_number' => '375431', 'model_name' => 'EFFECTA S', 'device_type' => 'Single Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 73000, 'mr_enabled' => false],
            ['model_number' => '377381', 'model_name' => 'ESTELLA DR MRI', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '377383', 'model_name' => 'Estella DR-T MRI', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '377385', 'model_name' => 'ESTELLA SR MRI', 'device_type' => 'Single Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '381468', 'model_name' => 'LUMAX 640 VR-T PRO MRI', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '381470', 'model_name' => 'LUMAX 640 DR-T PRO MRI', 'device_type' => 'Dual Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '381471', 'model_name' => 'LUMAX 640 HF-T PRO MRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '381534', 'model_name' => 'EVIA HF-T PRO MRI', 'device_type' => 'Triple Chamber Brady', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '383554', 'model_name' => 'Iforia 3 HF-T DF1', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '383556', 'model_name' => 'IFORIA 3 HFT DF-4', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '383570', 'model_name' => 'IFORIA 3 DRT DF-1', 'device_type' => 'Dual Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '383572', 'model_name' => 'Iforia 3 DR-T DF4', 'device_type' => 'Dual Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '383586', 'model_name' => 'IFORIA 3 VR-T DF1', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '383588', 'model_name' => 'IFORIA 3 VR-T DF4', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '390062', 'model_name' => 'IFORIA 7 HF-T Pro MRI DF4', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '390075', 'model_name' => 'IFORIA 7 DR-T ProMRI DF4', 'device_type' => 'Dual Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '390083', 'model_name' => 'IFORIA 7 VR-T ProMRI DF1', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '390089', 'model_name' => 'IFORIA 7 VR-T ProMRI DF4', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '390111', 'model_name' => 'IFORIA 5 HF-T MRI DF1', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '390113', 'model_name' => 'IFORIA 5 HF-T MRI DF4', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '390115', 'model_name' => 'IFORIA 5 DRT MRI DF1', 'device_type' => 'Dual Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '390117', 'model_name' => 'IFORIA 5 DRT MRI DF4', 'device_type' => 'Dual Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '390119', 'model_name' => 'IFORIA 5 VR-T DF-1 MRI', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '390121', 'model_name' => 'IFORIA 5 VR-T MRI DF4', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '390123', 'model_name' => 'Iforia 5 VR-T DX ProMRI DF-1', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '392416', 'model_name' => 'ITREVIA 5 DRT DF-1 MRI', 'device_type' => 'Dual Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '392417', 'model_name' => 'ITREVIA 5 DR-T DF1', 'device_type' => 'Dual Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '392421', 'model_name' => 'ITREVIA 5 DRT DF-4 MRI', 'device_type' => 'Dual Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '392422', 'model_name' => 'ITREVIA 5 DR-T DF4', 'device_type' => 'Dual Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '393048', 'model_name' => 'Iperia 5 VR-T DX DF-1 ProMRI', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '393054', 'model_name' => 'ITREVIA 5 VRT DX DF1 MRI', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '393055', 'model_name' => 'ITREVIA 5 VRT DX DF1', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '393056', 'model_name' => 'IFORIA 5 VR-T ProMRI DF1', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '393057', 'model_name' => 'ITREVIA 5 VRT DF-4 MRI', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '393058', 'model_name' => 'ITREVIA 5 VR-T DF1', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '393059', 'model_name' => 'ITREVIA 5 VR-T DF4', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '393063', 'model_name' => 'ITREVIA 5 HFT DF-4 MRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '393064', 'model_name' => 'ITREVIA 5 HFT DF-4', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '393065', 'model_name' => 'ITREVIA 5 HFT DF-1 MRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '393066', 'model_name' => 'ITREVIA 5 HFT DF-1', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '394928', 'model_name' => 'ETRINSA 6 DR', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '394940', 'model_name' => 'ETRINSA 6 SR', 'device_type' => 'Single Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '394976', 'model_name' => 'ETRINSA 8 HFT Pro MRI', 'device_type' => 'Triple Chamber Brady', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '394977', 'model_name' => 'ETRINSA 8 DRT MRI', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '401661', 'model_name' => 'ITREVIA 7 HF-T QP MRI DF4', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '402657', 'model_name' => 'Itrevia 5 HFT QP DF 4 IS 4  Pro MRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '402659', 'model_name' => 'ITREVIA 5 HF-T QP DF4', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => false],
            ['model_number' => '404627', 'model_name' => 'Intica 7 HF-T DF-1 IS-1     ProMRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '404629', 'model_name' => 'Intica 7 HF-T QP DF-1 IS4   ProMRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '404630', 'model_name' => 'Intica 7 HF-T QP DF4 IS4 ProMRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '404632', 'model_name' => 'Intica 7 DR-T DF4           ProMRI', 'device_type' => 'Dual Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '404633', 'model_name' => 'Intica 7 VR-T DX DF-1       ProMRI', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '404642', 'model_name' => 'INLEXA 7 VR-T DX DF1', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 1826, 'mr_enabled' => true],
            ['model_number' => '404683', 'model_name' => 'Intica 5 HF-T DF-1 IS-1     ProMRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '404684', 'model_name' => 'Intica 5 HF-T DF4 IS-1      ProMRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '404685', 'model_name' => 'Intica 5 HF-T QP DF4 IS4  ProMRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '404686', 'model_name' => 'Intica 5 DR-T DF-1          ProMRI', 'device_type' => 'Dual Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '404687', 'model_name' => 'Intica 5 DR-T DF4           ProMRI', 'device_type' => 'Dual Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '404688', 'model_name' => 'Intica 5 VR-T DX DF-1       ProMRI', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '404689', 'model_name' => 'Intica 5 VR-T DF-1          ProMRI', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '404690', 'model_name' => 'Intica 5 VR-T DF4           ProMRI', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '404699', 'model_name' => 'Inlexa 3 HF-T DF-1 IS-1 ProMRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 1826, 'mr_enabled' => true],
            ['model_number' => '404700', 'model_name' => 'Inlexa 3 HF-T DF4 IS-1 ProMRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 1826, 'mr_enabled' => true],
            ['model_number' => '404701', 'model_name' => 'Inlexa 3 DR-T DF-1 ProMRI', 'device_type' => 'Dual Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 1826, 'mr_enabled' => true],
            ['model_number' => '404702', 'model_name' => 'Inlexa 3 DR-T DF4 ProMRI', 'device_type' => 'Dual Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 1826, 'mr_enabled' => true],
            ['model_number' => '404703', 'model_name' => 'Inlexa 3 VR-T DF-1 ProMRI', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 1826, 'mr_enabled' => true],
            ['model_number' => '404704', 'model_name' => 'Inlexa 3 VR-T DF4 ProMRI', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 1826, 'mr_enabled' => true],
            ['model_number' => '406932', 'model_name' => 'Intica 5 HF-T QP DF-1 IS4   ProMRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 0, 'mr_enabled' => true],
            ['model_number' => '407139', 'model_name' => 'Evity 8 HF-T QP', 'device_type' => 'Triple Chamber Brady', 'cardiomessenger_enable' => true, 'warranty' => 1826, 'mr_enabled' => true],
            ['model_number' => '407140', 'model_name' => 'Evity 8 HF-T', 'device_type' => 'Triple Chamber Brady', 'cardiomessenger_enable' => true, 'warranty' => 1826, 'mr_enabled' => true],
            ['model_number' => '407141', 'model_name' => 'Enitra 8 HF-T QP', 'device_type' => 'Triple Chamber Brady', 'cardiomessenger_enable' => true, 'warranty' => 1826, 'mr_enabled' => true],
            ['model_number' => '407142', 'model_name' => 'ENITRA 8 HF-T', 'device_type' => 'Triple Chamber Brady', 'cardiomessenger_enable' => true, 'warranty' => 1826, 'mr_enabled' => true],
            ['model_number' => '407146', 'model_name' => 'Evity 8 DR-T', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => true, 'warranty' => 73000, 'mr_enabled' => true],
            ['model_number' => '407147', 'model_name' => 'Enitra 8 DR-T', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => true, 'warranty' => 73000, 'mr_enabled' => true],
            ['model_number' => '407149', 'model_name' => 'Evity 6 DR-T', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => true, 'warranty' => 73000, 'mr_enabled' => true],
            ['model_number' => '407150', 'model_name' => 'Enitra 6 DR-T', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => true, 'warranty' => 73000, 'mr_enabled' => true],
            ['model_number' => '407153', 'model_name' => 'Enitra 6 DR', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 73000, 'mr_enabled' => true],
            ['model_number' => '407155', 'model_name' => 'ENTICOS 4 DR', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 2921, 'mr_enabled' => true],
            ['model_number' => '407156', 'model_name' => 'ENTICOS 4 D', 'device_type' => 'Dual Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 2921, 'mr_enabled' => true],
            ['model_number' => '407158', 'model_name' => 'Evity 8 SR-T', 'device_type' => 'Single Chamber Brady', 'cardiomessenger_enable' => true, 'warranty' => 73000, 'mr_enabled' => true],
            ['model_number' => '407159', 'model_name' => 'Enitra 8 SR-T', 'device_type' => 'Single Chamber Brady', 'cardiomessenger_enable' => true, 'warranty' => 73000, 'mr_enabled' => true],
            ['model_number' => '407161', 'model_name' => 'Evity 6 SR-T', 'device_type' => 'Single Chamber Brady', 'cardiomessenger_enable' => true, 'warranty' => 73000, 'mr_enabled' => true],
            ['model_number' => '407162', 'model_name' => 'Enitra 6 SR-T', 'device_type' => 'Single Chamber Brady', 'cardiomessenger_enable' => true, 'warranty' => 73000, 'mr_enabled' => true],
            ['model_number' => '407165', 'model_name' => 'Enitra 6 SR', 'device_type' => 'Single Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 73000, 'mr_enabled' => true],
            ['model_number' => '407167', 'model_name' => 'ENTICOS 4 SR', 'device_type' => 'Single Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 3652, 'mr_enabled' => true],
            ['model_number' => '407168', 'model_name' => 'Enticos 4 S', 'device_type' => 'Single Chamber Brady', 'cardiomessenger_enable' => false, 'warranty' => 3652, 'mr_enabled' => true],
            ['model_number' => '416037', 'model_name' => 'Inlexa 3 HF-T QP DF-1 IS4 ProMRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 1826, 'mr_enabled' => true],
            ['model_number' => '416038', 'model_name' => 'Inlexa 3 HF-T QP DF4 IS4 ProMRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 1826, 'mr_enabled' => true],
            ['model_number' => '429532', 'model_name' => 'Rivacor 7 HF-T QP DF4 IS4 ProMRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 2191, 'mr_enabled' => true],
            ['model_number' => '429533', 'model_name' => 'Rivacor 7 HF-T DF4 IS-1 ProMRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 2191, 'mr_enabled' => true],
            ['model_number' => '429534', 'model_name' => 'Rivacor 7 DR-T DF4 ProMRI', 'device_type' => 'Dual Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 2921, 'mr_enabled' => true],
            ['model_number' => '429535', 'model_name' => 'Rivacor 7 VR-T DX DF4 ProMRI', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 3652, 'mr_enabled' => true],
            ['model_number' => '429536', 'model_name' => 'Rivacor 7 VR-T DF4 ProMRI', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 3652, 'mr_enabled' => true],
            ['model_number' => '429552', 'model_name' => 'Intica Neo 7 HF-T QP DF-1 IS4 ProMRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 2191, 'mr_enabled' => true],
            ['model_number' => '429553', 'model_name' => 'Intica Neo 7 HF-T DF-1 IS-1 ProMRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 2191, 'mr_enabled' => true],
            ['model_number' => '429558', 'model_name' => 'Intica Neo 7 DR-T DF-1 ProMRI', 'device_type' => 'Dual Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 2921, 'mr_enabled' => true],
            ['model_number' => '429559', 'model_name' => 'Intica Neo 7 VR-T DX DF-1 ProMRI', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 3652, 'mr_enabled' => true],
            ['model_number' => '429560', 'model_name' => 'Intica Neo 7 VR-T DF-1 ProMRI', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 3652, 'mr_enabled' => true],
            ['model_number' => '429561', 'model_name' => 'Rivacor 5 HF-T QP DF4 IS4 ProMRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 2191, 'mr_enabled' => true],
            ['model_number' => '429562', 'model_name' => 'Rivacor 5 HF-T DF4 IS-1 ProMRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 2191, 'mr_enabled' => true],
            ['model_number' => '429563', 'model_name' => 'Rivacor 5 DR-T DF4 ProMRI', 'device_type' => 'Dual Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 2921, 'mr_enabled' => true],
            ['model_number' => '429564', 'model_name' => 'Rivacor 5 VR-T DX DF4 ProMRI', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 3652, 'mr_enabled' => true],
            ['model_number' => '429565', 'model_name' => 'Rivacor 5 VR-T DF4 ProMRI', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 3652, 'mr_enabled' => true],
            ['model_number' => '429566', 'model_name' => 'Intica Neo 5 HF-T QP DF-1 IS4 ProMRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 2191, 'mr_enabled' => true],
            ['model_number' => '429567', 'model_name' => 'Intica Neo 5 HF-T DF-1 IS-1 ProMRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 2191, 'mr_enabled' => true],
            ['model_number' => '429568', 'model_name' => 'Intica Neo 5 DR-T DF-1 ProMRI', 'device_type' => 'Dual Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 2921, 'mr_enabled' => true],
            ['model_number' => '429569', 'model_name' => 'Intica Neo 5 VR-T DX DF-1 ProMRI', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 3652, 'mr_enabled' => true],
            ['model_number' => '429570', 'model_name' => 'Intica Neo 5 VR-T DF-1 ProMRI', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 3652, 'mr_enabled' => true],
            ['model_number' => '429571', 'model_name' => 'Rivacor 3 HF-T QP DF4 IS4 ProMRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 2191, 'mr_enabled' => true],
            ['model_number' => '429572', 'model_name' => 'Rivacor 3 HF-T DF4 IS-1 ProMRI', 'device_type' => 'Triple Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 2191, 'mr_enabled' => true],
            ['model_number' => '429573', 'model_name' => 'Rivacor 3 DR-T DF4 ProMRI', 'device_type' => 'Dual Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 2921, 'mr_enabled' => true],
            ['model_number' => '429574', 'model_name' => 'Rivacor 3 VR-T DF4 ProMRI', 'device_type' => 'Single Chamber Tachy', 'cardiomessenger_enable' => true, 'warranty' => 3652, 'mr_enabled' => true],
        ];

        foreach ($models as $model) {
            IpgModel::updateOrCreate(
                ['model_number' => $model['model_number']],
                $model
            );
        }

        Log::info('IpgModelSeeder completed successfully.');
    }
}